name: new Basic Workflow Dispatch Example

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: false
        default: 'dev'  # Default branch is set to 'dev'
        type: string
      environment:
        description: 'Choose the environment (e.g., master, production)'
        required: true
        default: 'production'  # Default environment if no input is provided
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest  # The runner will be an Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Display selected environment
      run: |
        echo "Deploying to the ${{ github.event.inputs.environment }} environment"
        echo "Using branch: ${{ github.event.inputs.branch }}"

    - name: Run deployment script
      run: echo "We did the thing!"  # Placeholder for actual deployment or script
