name: Prevent Non-Admin Merges

on:
  pull_request:
    branches:
      - main

jobs:
  check-admin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get user info
      run: |
        echo "User making the PR: ${{ github.actor }}"
        ADMIN_USERS=("Veenayadav02")  # Add your GitHub username(s) here

        if [[ ! " ${ADMIN_USERS[@]} " =~ " ${GITHUB_ACTOR} " ]]; then
          echo "Error: Only admins can merge to the main branch." 
          exit 1
        fi
